import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const now = Date.now();
    
    const sampleProducts = [
        {
            name: 'Ragi Chocolate Walnut Brownies',
            slug: 'ragi-chocolate-walnut-brownies',
            category: 'Health-Focused Bakery',
            subCategory: 'low-sugar',
            description: 'Rich, fudgy brownies made with ragi flour and premium dark chocolate. Packed with walnuts for added crunch and omega-3s, these guilt-free treats are perfect for satisfying your sweet cravings while staying healthy.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/ragi-chocolate-walnut-brownies.jpg',
            badge: 'Bestseller',
            featured: 1,
            rating: 4.8,
            reviews: 187,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Quinoa Banana Bread',
            slug: 'quinoa-banana-bread',
            category: 'Health-Focused Bakery',
            subCategory: 'protein-rich',
            description: 'Moist and flavorful banana bread enhanced with protein-rich quinoa flour. Made with ripe bananas and natural sweeteners, this wholesome loaf is perfect for breakfast or as an energizing snack throughout the day.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/quinoa-banana-bread.jpg',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 142,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Multigrain Digestive Cookies',
            slug: 'multigrain-digestive-cookies',
            category: 'Health-Focused Bakery',
            subCategory: 'high-fiber',
            description: 'Crunchy digestive cookies crafted from a blend of whole wheat, oats, and millet. High in dietary fiber and made with minimal sugar, these cookies support digestive health while delivering authentic biscuit flavor.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/multigrain-digestive-cookies.jpg',
            badge: 'New Arrival',
            featured: 1,
            rating: 4.7,
            reviews: 156,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Besan Ladoo Cookies',
            slug: 'besan-ladoo-cookies',
            category: 'Health-Focused Bakery',
            subCategory: 'gluten-free',
            description: 'Traditional Indian besan ladoo reimagined as delightful gluten-free cookies. Made with roasted gram flour, ghee, and cardamom, these protein-packed treats bring nostalgic flavors in a convenient, modern format.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/besan-ladoo-cookies.jpg',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 98,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Jowar Coconut Muffins',
            slug: 'jowar-coconut-muffins',
            category: 'Health-Focused Bakery',
            subCategory: 'gluten-free',
            description: 'Light and fluffy muffins made with jowar (sorghum) flour and fresh coconut. These gluten-free delights are naturally low in calories and high in nutrients, perfect for health-conscious snacking.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/jowar-coconut-muffins.jpg',
            badge: 'Low Cal',
            featured: 0,
            rating: 4.4,
            reviews: 89,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Date & Walnut Cake Bars',
            slug: 'date-walnut-cake-bars',
            category: 'Health-Focused Bakery',
            subCategory: 'low-sugar',
            description: 'Dense, naturally sweet cake bars made with dates and walnuts. Sweetened only with dates, these bars provide sustained energy without refined sugar, making them ideal for pre or post-workout fuel.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/date-walnut-cake-bars.jpg',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 124,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Almond Flour Nankhatai',
            slug: 'almond-flour-nankhatai',
            category: 'Health-Focused Bakery',
            subCategory: 'protein-rich',
            description: 'Classic Indian shortbread cookies reimagined with nutrient-dense almond flour. These melt-in-mouth nankhatai are high in protein and healthy fats, offering traditional taste with modern nutrition.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/almond-flour-nankhatai.jpg',
            badge: 'Bestseller',
            featured: 1,
            rating: 4.9,
            reviews: 234,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Whole Wheat Til Cookies',
            slug: 'whole-wheat-til-cookies',
            category: 'Health-Focused Bakery',
            subCategory: 'high-fiber',
            description: 'Nutty cookies made with whole wheat flour and roasted sesame seeds (til). Rich in calcium and dietary fiber, these cookies offer the perfect balance of nutrition and taste with every crunchy bite.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/whole-wheat-til-cookies.jpg',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 76,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Ragi Finger Millet Sticks',
            slug: 'ragi-finger-millet-sticks',
            category: 'Ancient Grains Collection',
            subCategory: 'superfood',
            description: 'Crispy, savory sticks made from calcium-rich ragi (finger millet). This traditional superfood is packed with essential amino acids and minerals, making these sticks a perfect guilt-free snack for all ages.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/ragi-finger-millet-sticks.jpg',
            badge: 'Superfood',
            featured: 1,
            rating: 4.7,
            reviews: 168,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Bajra Masala Crackers',
            slug: 'bajra-masala-crackers',
            category: 'Ancient Grains Collection',
            subCategory: 'gluten-free',
            description: 'Spiced crackers made from pearl millet (bajra) with traditional Indian masala blend. Naturally gluten-free and rich in iron, these crackers are perfect for evening snacking with tea or as a healthy appetizer.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/bajra-masala-crackers.jpg',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 112,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Quinoa Puff Energy Balls',
            slug: 'quinoa-puff-energy-balls',
            category: 'Ancient Grains Collection',
            subCategory: 'protein-rich',
            description: 'Bite-sized energy balls made with puffed quinoa, dates, and nuts. These complete protein powerhouses provide sustained energy and are perfect for on-the-go snacking or post-workout recovery.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/quinoa-puff-energy-balls.jpg',
            badge: 'High Protein',
            featured: 1,
            rating: 4.8,
            reviews: 201,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Amaranth Chikki Bars',
            slug: 'amaranth-chikki-bars',
            category: 'Ancient Grains Collection',
            subCategory: 'superfood',
            description: 'Traditional Indian chikki made with popped amaranth (rajgira) and jaggery. Rich in lysine and calcium, these bars combine ancient grain nutrition with the nostalgic taste of homemade chikki.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/amaranth-chikki-bars.jpg',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 134,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Multi-Millet Namkeen Mix',
            slug: 'multi-millet-namkeen-mix',
            category: 'Ancient Grains Collection',
            subCategory: 'high-fiber',
            description: 'Crunchy savory mix featuring five different millets seasoned with aromatic spices. High in fiber and micronutrients, this namkeen offers a healthier alternative to traditional fried snacks.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/multi-millet-namkeen-mix.jpg',
            badge: 'New Arrival',
            featured: 0,
            rating: 4.5,
            reviews: 95,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Ragi Chakli Spirals',
            slug: 'ragi-chakli-spirals',
            category: 'Ancient Grains Collection',
            subCategory: 'gluten-free',
            description: 'Traditional Maharashtrian chakli reimagined with ragi flour. These spiral-shaped snacks are baked instead of fried, offering the same festive flavor with added nutrition and lower calories.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/ragi-chakli-spirals.jpg',
            badge: null,
            featured: 0,
            rating: 4.7,
            reviews: 147,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Jowar Puffs Bhel Mix',
            slug: 'jowar-puffs-bhel-mix',
            category: 'Ancient Grains Collection',
            subCategory: 'low-sugar',
            description: 'Light and airy bhel mix made with puffed jowar, roasted peanuts, and spices. A healthier take on the Mumbai street food favorite, perfect for satisfying savory cravings without guilt.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/jowar-puffs-bhel-mix.jpg',
            badge: 'Low Cal',
            featured: 0,
            rating: 4.4,
            reviews: 82,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Bajra Methi Khakhra',
            slug: 'bajra-methi-khakhra',
            category: 'Ancient Grains Collection',
            subCategory: 'high-fiber',
            description: 'Thin, crispy khakhra made with pearl millet and fresh fenugreek leaves. This Gujarati specialty is high in iron and fiber, perfect for a light breakfast or healthy tea-time snack.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/bajra-methi-khakhra.jpg',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 118,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Coconut Dates Energy Bars',
            slug: 'coconut-dates-energy-bars',
            category: 'Vegan Options',
            subCategory: 'vegan',
            description: 'Wholesome energy bars made with Medjool dates and desiccated coconut. Completely plant-based and naturally sweetened, these bars provide quick energy and sustained stamina for active lifestyles.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/coconut-dates-energy-bars.jpg',
            badge: 'Bestseller',
            featured: 1,
            rating: 4.8,
            reviews: 192,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Cashew Cranberry Bites',
            slug: 'cashew-cranberry-bites',
            category: 'Vegan Options',
            subCategory: 'vegan',
            description: 'Delicious bite-sized treats combining roasted cashews with tangy dried cranberries. These vegan snacks are rich in antioxidants and healthy fats, perfect for a nutritious pick-me-up.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/cashew-cranberry-bites.jpg',
            badge: null,
            featured: 0,
            rating: 4.7,
            reviews: 156,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Peanut Jaggery Chikki',
            slug: 'peanut-jaggery-chikki',
            category: 'Vegan Options',
            subCategory: 'vegan',
            description: 'Classic Indian chikki made with roasted peanuts and organic jaggery. This vegan-friendly treat is rich in protein and iron, offering traditional taste without any animal products.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/peanut-jaggery-chikki.jpg',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 128,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Dry Fruit Ladoo Mix',
            slug: 'dry-fruit-ladoo-mix',
            category: 'Vegan Options',
            subCategory: 'vegan',
            description: 'Nutritious ladoos made from a premium blend of almonds, cashews, dates, and figs. These plant-based energy balls are packed with vitamins and minerals, perfect for festive gifting or daily nutrition.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/dry-fruit-ladoo-mix.jpg',
            badge: 'New Arrival',
            featured: 0,
            rating: 4.6,
            reviews: 103,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Mini Ragi Chocolate Cookies',
            slug: 'mini-ragi-chocolate-cookies',
            category: "Kids' Healthy Treats",
            subCategory: 'low-sugar',
            description: 'Kid-friendly mini cookies made with ragi flour and real chocolate chips. Lightly sweetened and packed with calcium, these treats make healthy snacking fun for children while supporting their growth.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/mini-ragi-chocolate-cookies.jpg',
            badge: 'Bestseller',
            featured: 0,
            rating: 4.9,
            reviews: 245,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Honey Oats Granola Bars',
            slug: 'honey-oats-granola-bars',
            category: "Kids' Healthy Treats",
            subCategory: 'protein-rich',
            description: 'Crunchy granola bars made with rolled oats, honey, and mixed nuts. Perfect for school lunch boxes, these bars provide sustained energy and essential nutrients for active, growing children.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/honey-oats-granola-bars.jpg',
            badge: null,
            featured: 0,
            rating: 4.7,
            reviews: 178,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Fruit & Nut Trail Mix',
            slug: 'fruit-nut-trail-mix',
            category: "Kids' Healthy Treats",
            subCategory: 'superfood',
            description: 'Colorful trail mix combining dried fruits, roasted nuts, and seeds. Designed for young taste buds, this superfood blend supports brain development and provides healthy snacking for active kids.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/fruit-nut-trail-mix.jpg',
            badge: 'Superfood',
            featured: 0,
            rating: 4.6,
            reviews: 164,
            createdAt: now,
            updatedAt: now,
        },
        {
            name: 'Turmeric Jaggery Pops',
            slug: 'turmeric-jaggery-pops',
            category: "Kids' Healthy Treats",
            subCategory: 'superfood',
            description: 'Fun, bite-sized pops infused with turmeric and sweetened with jaggery. These immunity-boosting treats help children develop a taste for traditional Indian superfoods in an appealing, kid-friendly format.',
            imageUrl: 'https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/turmeric-jaggery-pops.jpg',
            badge: 'New Arrival',
            featured: 0,
            rating: 4.5,
            reviews: 87,
            createdAt: now,
            updatedAt: now,
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log(`✅ Successfully seeded ${sampleProducts.length} products to the database`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});