import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            name: 'Stevia Cookie Pack',
            slug: 'stevia-cookie-pack',
            category: 'Sugar-Free',
            imageUrl: '/images/products/stevia-cookies.jpg',
            badge: 'Sugar-Free',
            healthGoal: 'low-sugar',
            rating: '4.8',
            reviewsCount: 124,
            description: 'Delicious cookies sweetened with natural stevia, perfect for guilt-free snacking.',
            protein: '5g',
            carbs: '18g',
            fat: '6g',
            calories: '150',
            isActive: true,
            sortOrder: 1,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Jaggery Energy Bites',
            slug: 'jaggery-energy-bites',
            category: 'Natural Energy',
            imageUrl: '/images/products/jaggery-bites.jpg',
            badge: 'Natural',
            healthGoal: 'energy-boost',
            rating: '4.7',
            reviewsCount: 98,
            description: 'Natural energy bites made with organic jaggery and wholesome ingredients.',
            protein: '6g',
            carbs: '25g',
            fat: '8g',
            calories: '190',
            isActive: true,
            sortOrder: 2,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Sugar-Free Brownies',
            slug: 'sugar-free-brownies',
            category: 'Low Sugar',
            imageUrl: '/images/products/sugar-free-brownies.jpg',
            badge: 'Best Seller',
            healthGoal: 'low-sugar',
            rating: '4.9',
            reviewsCount: 156,
            description: 'Decadent brownies with zero added sugar, made with healthy alternatives.',
            protein: '7g',
            carbs: '20g',
            fat: '9g',
            calories: '180',
            isActive: true,
            sortOrder: 3,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Oat & Millet Cookies',
            slug: 'oat-millet-cookies',
            category: 'High Fiber',
            imageUrl: '/images/products/oat-millet-cookies.jpg',
            badge: 'High Fiber',
            healthGoal: 'digestive-health',
            rating: '4.6',
            reviewsCount: 87,
            description: 'Wholesome cookies packed with oats and millet for a fiber-rich snack.',
            protein: '4g',
            carbs: '22g',
            fat: '7g',
            calories: '160',
            isActive: true,
            sortOrder: 4,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Flax Seed Crackers',
            slug: 'flax-seed-crackers',
            category: 'High Protein',
            imageUrl: '/images/products/flax-crackers.jpg',
            badge: 'High Protein',
            healthGoal: 'protein-rich',
            rating: '4.5',
            reviewsCount: 72,
            description: 'Crunchy crackers loaded with flax seeds for a protein-packed snack.',
            protein: '8g',
            carbs: '15g',
            fat: '10g',
            calories: '170',
            isActive: true,
            sortOrder: 5,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Oat Protein Bites',
            slug: 'oat-protein-bites',
            category: 'High Protein',
            imageUrl: '/images/products/oat-protein-bites.jpg',
            badge: 'New',
            healthGoal: 'protein-rich',
            rating: '4.7',
            reviewsCount: 63,
            description: 'Power-packed protein bites made with premium oats and plant protein.',
            protein: '9g',
            carbs: '19g',
            fat: '6g',
            calories: '175',
            isActive: true,
            sortOrder: 6,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});