import { db } from '@/db';
import { products, productImages, productNutrition, productIngredients, productHighlights } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Health-Focused Bakery (8 products)
        {
            name: 'Ragi Chocolate Walnut Brownies',
            slug: 'ragi-chocolate-walnut-brownies',
            category: 'Health-Focused Bakery',
            sub_category: 'low-sugar',
            description: 'Decadent chocolate brownies made with nutrient-rich ragi flour and crunchy walnuts. These brownies are naturally sweetened and packed with calcium and iron from finger millet, making guilt-free indulgence possible.',
            badge: 'Bestseller',
            featured: 1,
            rating: 4.8,
            reviews: 187,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Quinoa Banana Bread',
            slug: 'quinoa-banana-bread',
            category: 'Health-Focused Bakery',
            sub_category: 'protein-rich',
            description: 'Moist and flavorful banana bread enriched with protein-packed quinoa flour. A perfect breakfast option that combines the natural sweetness of ripe bananas with the complete protein profile of quinoa.',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 142,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Multigrain Digestive Cookies',
            slug: 'multigrain-digestive-cookies',
            category: 'Health-Focused Bakery',
            sub_category: 'high-fiber',
            description: 'Crunchy digestive cookies made with a blend of whole wheat, oats, and ragi. High in dietary fiber and perfect for aiding digestion while satisfying your tea-time cravings.',
            badge: 'New Arrival',
            featured: 1,
            rating: 4.7,
            reviews: 156,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Besan Ladoo Cookies',
            slug: 'besan-ladoo-cookies',
            category: 'Health-Focused Bakery',
            sub_category: 'gluten-free',
            description: 'Traditional Indian besan ladoo flavors transformed into delightful gluten-free cookies. Made with pure chickpea flour and ghee, these cookies bring the authentic taste of homemade ladoos in a convenient cookie form.',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 98,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Jowar Coconut Muffins',
            slug: 'jowar-coconut-muffins',
            category: 'Health-Focused Bakery',
            sub_category: 'gluten-free',
            description: 'Light and fluffy muffins made with jowar flour and fresh coconut. These gluten-free muffins are naturally sweetened with jaggery and provide sustained energy throughout the day.',
            badge: 'Low Cal',
            featured: 0,
            rating: 4.4,
            reviews: 89,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Date & Walnut Cake Bars',
            slug: 'date-walnut-cake-bars',
            category: 'Health-Focused Bakery',
            sub_category: 'low-sugar',
            description: 'Rich and moist cake bars naturally sweetened with dates and studded with walnuts. A perfect on-the-go snack that provides natural energy from dates and omega-3s from walnuts.',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 124,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Almond Flour Nankhatai',
            slug: 'almond-flour-nankhatai',
            category: 'Health-Focused Bakery',
            sub_category: 'protein-rich',
            description: 'Classic Indian shortbread cookies reimagined with protein-rich almond flour. These melt-in-mouth nankhatais are low in carbs and high in healthy fats, perfect for a keto-friendly treat.',
            badge: 'Bestseller',
            featured: 1,
            rating: 4.9,
            reviews: 234,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Whole Wheat Til Cookies',
            slug: 'whole-wheat-til-cookies',
            category: 'Health-Focused Bakery',
            sub_category: 'high-fiber',
            description: 'Nutritious cookies made with whole wheat flour and roasted sesame seeds. Rich in calcium and iron from til, these cookies support bone health while providing a delightful nutty flavor.',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 76,
            created_at: new Date(),
            updated_at: new Date(),
        },

        // Ancient Grains Collection (8 products)
        {
            name: 'Ragi Finger Millet Sticks',
            slug: 'ragi-finger-millet-sticks',
            category: 'Ancient Grains Collection',
            sub_category: 'superfood',
            description: 'Crispy and savory sticks made from pure ragi flour with aromatic Indian spices. Packed with calcium and iron, these superfood snacks support bone health and boost hemoglobin levels naturally.',
            badge: 'Superfood',
            featured: 1,
            rating: 4.7,
            reviews: 168,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Bajra Masala Crackers',
            slug: 'bajra-masala-crackers',
            category: 'Ancient Grains Collection',
            sub_category: 'gluten-free',
            description: 'Thin and crispy crackers made from pearl millet with a perfect blend of Indian masalas. Gluten-free and rich in magnesium, these crackers are ideal for pairing with dips or enjoying on their own.',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 112,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Quinoa Puff Energy Balls',
            slug: 'quinoa-puff-energy-balls',
            category: 'Ancient Grains Collection',
            sub_category: 'protein-rich',
            description: 'Power-packed energy balls made with puffed quinoa, dates, and nuts. Each ball delivers complete protein and sustained energy, perfect for pre-workout fuel or midday energy boost.',
            badge: 'High Protein',
            featured: 1,
            rating: 4.8,
            reviews: 201,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Amaranth Chikki Bars',
            slug: 'amaranth-chikki-bars',
            category: 'Ancient Grains Collection',
            sub_category: 'superfood',
            description: 'Traditional Indian chikki elevated with protein-rich amaranth seeds and organic jaggery. These bars combine ancient nutrition with authentic taste, providing iron and calcium in every bite.',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 134,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Multi-Millet Namkeen Mix',
            slug: 'multi-millet-namkeen-mix',
            category: 'Ancient Grains Collection',
            sub_category: 'high-fiber',
            description: 'Crunchy savory mix combining bajra, jowar, and ragi with roasted nuts and spices. High in dietary fiber and minerals, this namkeen satisfies cravings while supporting digestive health.',
            badge: 'New Arrival',
            featured: 0,
            rating: 4.5,
            reviews: 95,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Ragi Chakli Spirals',
            slug: 'ragi-chakli-spirals',
            category: 'Ancient Grains Collection',
            sub_category: 'gluten-free',
            description: 'Authentic South Indian chakli made with ragi flour and traditional spices. These crispy spirals are gluten-free and packed with the goodness of finger millet, perfect for festive snacking.',
            badge: null,
            featured: 0,
            rating: 4.7,
            reviews: 147,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Jowar Puffs Bhel Mix',
            slug: 'jowar-puffs-bhel-mix',
            category: 'Ancient Grains Collection',
            sub_category: 'low-sugar',
            description: 'Light and airy jowar puffs mixed with roasted peanuts, curry leaves, and spices. A healthier alternative to traditional bhel, this mix is low in sugar and calories while being high in flavor.',
            badge: 'Low Cal',
            featured: 0,
            rating: 4.4,
            reviews: 82,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Bajra Methi Khakhra',
            slug: 'bajra-methi-khakhra',
            category: 'Ancient Grains Collection',
            sub_category: 'high-fiber',
            description: 'Thin and crispy Gujarati khakhras made with bajra flour and fresh fenugreek leaves. Rich in fiber and iron, these khakhras aid digestion and help regulate blood sugar levels.',
            badge: null,
            featured: 0,
            rating: 4.6,
            reviews: 118,
            created_at: new Date(),
            updated_at: new Date(),
        },

        // Vegan Options (4 products)
        {
            name: 'Coconut Dates Energy Bars',
            slug: 'coconut-dates-energy-bars',
            category: 'Vegan Options',
            sub_category: 'vegan',
            description: 'Wholesome energy bars made with fresh coconut and Medjool dates without any animal products. These vegan bars provide instant energy and are rich in medium-chain fatty acids and natural sugars.',
            badge: 'Bestseller',
            featured: 1,
            rating: 4.8,
            reviews: 192,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Cashew Cranberry Bites',
            slug: 'cashew-cranberry-bites',
            category: 'Vegan Options',
            sub_category: 'vegan',
            description: 'Delicious bite-sized snacks combining roasted cashews with tangy cranberries. Completely plant-based and packed with healthy fats, these bites support heart health and provide antioxidants.',
            badge: null,
            featured: 0,
            rating: 4.7,
            reviews: 156,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Peanut Jaggery Chikki',
            slug: 'peanut-jaggery-chikki',
            category: 'Vegan Options',
            sub_category: 'vegan',
            description: 'Traditional Indian peanut brittle made with organic jaggery and roasted peanuts. This vegan-friendly chikki is iron-rich and provides sustained energy while satisfying sweet cravings naturally.',
            badge: null,
            featured: 0,
            rating: 4.5,
            reviews: 128,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Dry Fruit Ladoo Mix',
            slug: 'dry-fruit-ladoo-mix',
            category: 'Vegan Options',
            sub_category: 'vegan',
            description: 'Nutritious ladoos made with a blend of almonds, cashews, pistachios, and dates. These dairy-free ladoos are rich in omega-3s and provide complete nutrition in traditional Indian style.',
            badge: 'New Arrival',
            featured: 0,
            rating: 4.6,
            reviews: 103,
            created_at: new Date(),
            updated_at: new Date(),
        },

        // Kids' Healthy Treats (4 products)
        {
            name: 'Mini Ragi Chocolate Cookies',
            slug: 'mini-ragi-chocolate-cookies',
            category: "Kids' Healthy Treats",
            sub_category: 'low-sugar',
            description: 'Bite-sized chocolate cookies made with ragi flour, perfect for little hands. These fun cookies combine the goodness of finger millet with natural cocoa, providing calcium and iron for growing kids.',
            badge: 'Bestseller',
            featured: 0,
            rating: 4.9,
            reviews: 245,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Honey Oats Granola Bars',
            slug: 'honey-oats-granola-bars',
            category: "Kids' Healthy Treats",
            sub_category: 'protein-rich',
            description: 'Chewy granola bars made with rolled oats, nuts, and pure honey. These protein-rich bars are ideal for school lunchboxes, providing sustained energy for active kids throughout the day.',
            badge: null,
            featured: 0,
            rating: 4.7,
            reviews: 178,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Fruit & Nut Trail Mix',
            slug: 'fruit-nut-trail-mix',
            category: "Kids' Healthy Treats",
            sub_category: 'superfood',
            description: 'Colorful trail mix combining dried fruits, roasted nuts, and seeds. This superfood blend supports brain development and provides essential nutrients, making healthy snacking fun for children.',
            badge: 'Superfood',
            featured: 0,
            rating: 4.6,
            reviews: 164,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Turmeric Jaggery Pops',
            slug: 'turmeric-jaggery-pops',
            category: "Kids' Healthy Treats",
            sub_category: 'superfood',
            description: 'Innovative immunity-boosting pops made with turmeric and jaggery. These golden pops combine traditional Ayurvedic benefits with modern taste, helping build natural immunity in kids.',
            badge: 'New Arrival',
            featured: 0,
            rating: 4.5,
            reviews: 87,
            created_at: new Date(),
            updated_at: new Date(),
        },
    ];

    const insertedProducts = await db.insert(products).values(sampleProducts).returning();
    console.log(`✅ Inserted ${insertedProducts.length} products`);

    const productImagesData = insertedProducts.map((product) => ({
        product_id: product.id,
        image_url: `https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/${product.slug}-1.jpg`,
        alt_text: `${product.name} product image`,
        display_order: 1,
        is_primary: 1,
        created_at: new Date(),
    }));

    await db.insert(productImages).values(productImagesData);
    console.log(`✅ Inserted ${productImagesData.length} product images`);

    const nutritionData = [
        // Health-Focused Bakery
        { product_id: insertedProducts[0].id, serving_size: '2 brownies (60g)', calories: 245, protein: 6.5, carbs: 28.0, fat: 12.0, fiber: 5.5, sugar: 12.0 },
        { product_id: insertedProducts[1].id, serving_size: '1 slice (70g)', calories: 210, protein: 8.0, carbs: 32.0, fat: 6.5, fiber: 4.5, sugar: 14.0 },
        { product_id: insertedProducts[2].id, serving_size: '4 cookies (50g)', calories: 195, protein: 5.5, carbs: 28.0, fat: 7.0, fiber: 6.0, sugar: 8.0 },
        { product_id: insertedProducts[3].id, serving_size: '3 cookies (45g)', calories: 220, protein: 7.0, carbs: 24.0, fat: 11.0, fiber: 4.0, sugar: 9.0 },
        { product_id: insertedProducts[4].id, serving_size: '2 muffins (75g)', calories: 185, protein: 4.5, carbs: 26.0, fat: 7.5, fiber: 5.0, sugar: 11.0 },
        { product_id: insertedProducts[5].id, serving_size: '1 bar (55g)', calories: 230, protein: 6.0, carbs: 30.0, fat: 10.0, fiber: 5.5, sugar: 15.0 },
        { product_id: insertedProducts[6].id, serving_size: '3 pieces (40g)', calories: 240, protein: 9.0, carbs: 18.0, fat: 14.0, fiber: 3.5, sugar: 6.0 },
        { product_id: insertedProducts[7].id, serving_size: '4 cookies (45g)', calories: 180, protein: 5.0, carbs: 25.0, fat: 7.0, fiber: 6.5, sugar: 7.0 },
        // Ancient Grains Collection
        { product_id: insertedProducts[8].id, serving_size: '1 pack (40g)', calories: 165, protein: 5.5, carbs: 24.0, fat: 5.5, fiber: 6.0, sugar: 3.0 },
        { product_id: insertedProducts[9].id, serving_size: '8 crackers (35g)', calories: 145, protein: 4.5, carbs: 22.0, fat: 4.5, fiber: 5.5, sugar: 2.5 },
        { product_id: insertedProducts[10].id, serving_size: '3 balls (45g)', calories: 200, protein: 10.0, carbs: 26.0, fat: 7.0, fiber: 4.5, sugar: 12.0 },
        { product_id: insertedProducts[11].id, serving_size: '1 bar (50g)', calories: 215, protein: 7.5, carbs: 32.0, fat: 6.5, fiber: 5.0, sugar: 14.0 },
        { product_id: insertedProducts[12].id, serving_size: '1 cup (40g)', calories: 170, protein: 5.0, carbs: 24.0, fat: 6.0, fiber: 7.0, sugar: 3.5 },
        { product_id: insertedProducts[13].id, serving_size: '6 pieces (45g)', calories: 185, protein: 5.5, carbs: 26.0, fat: 7.0, fiber: 5.5, sugar: 4.0 },
        { product_id: insertedProducts[14].id, serving_size: '1 bowl (35g)', calories: 140, protein: 4.0, carbs: 22.0, fat: 4.5, fiber: 5.0, sugar: 2.0 },
        { product_id: insertedProducts[15].id, serving_size: '4 khakhras (40g)', calories: 155, protein: 4.5, carbs: 24.0, fat: 4.0, fiber: 6.5, sugar: 2.5 },
        // Vegan Options
        { product_id: insertedProducts[16].id, serving_size: '1 bar (50g)', calories: 220, protein: 4.5, carbs: 30.0, fat: 9.0, fiber: 5.5, sugar: 15.0 },
        { product_id: insertedProducts[17].id, serving_size: '10 bites (45g)', calories: 235, protein: 6.5, carbs: 24.0, fat: 13.0, fiber: 4.0, sugar: 11.0 },
        { product_id: insertedProducts[18].id, serving_size: '1 piece (50g)', calories: 250, protein: 8.0, carbs: 28.0, fat: 12.0, fiber: 3.5, sugar: 13.0 },
        { product_id: insertedProducts[19].id, serving_size: '2 ladoos (55g)', calories: 260, protein: 7.5, carbs: 26.0, fat: 14.0, fiber: 4.5, sugar: 14.0 },
        // Kids' Healthy Treats
        { product_id: insertedProducts[20].id, serving_size: '6 mini cookies (35g)', calories: 155, protein: 4.0, carbs: 22.0, fat: 6.0, fiber: 4.5, sugar: 9.0 },
        { product_id: insertedProducts[21].id, serving_size: '1 bar (45g)', calories: 190, protein: 6.5, carbs: 28.0, fat: 6.5, fiber: 5.0, sugar: 11.0 },
        { product_id: insertedProducts[22].id, serving_size: '1/4 cup (35g)', calories: 175, protein: 5.5, carbs: 20.0, fat: 8.5, fiber: 4.0, sugar: 10.0 },
        { product_id: insertedProducts[23].id, serving_size: '4 pops (40g)', calories: 165, protein: 4.0, carbs: 26.0, fat: 5.0, fiber: 3.5, sugar: 13.0 },
    ];

    await db.insert(productNutrition).values(nutritionData);
    console.log(`✅ Inserted ${nutritionData.length} nutrition records`);

    const highlightsData = [
        // Ragi Chocolate Walnut Brownies
        { product_id: insertedProducts[0].id, highlight_text: 'Rich in calcium from ragi flour', display_order: 1 },
        { product_id: insertedProducts[0].id, highlight_text: 'Naturally sweetened with dates', display_order: 2 },
        { product_id: insertedProducts[0].id, highlight_text: 'Omega-3 rich walnuts', display_order: 3 },
        { product_id: insertedProducts[0].id, highlight_text: 'No refined sugar', display_order: 4 },
        // Quinoa Banana Bread
        { product_id: insertedProducts[1].id, highlight_text: 'Complete protein from quinoa', display_order: 1 },
        { product_id: insertedProducts[1].id, highlight_text: 'Naturally sweet with ripe bananas', display_order: 2 },
        { product_id: insertedProducts[1].id, highlight_text: 'High in potassium', display_order: 3 },
        { product_id: insertedProducts[1].id, highlight_text: 'Perfect breakfast option', display_order: 4 },
        // Multigrain Digestive Cookies
        { product_id: insertedProducts[2].id, highlight_text: 'Aids digestion naturally', display_order: 1 },
        { product_id: insertedProducts[2].id, highlight_text: 'Blend of multiple whole grains', display_order: 2 },
        { product_id: insertedProducts[2].id, highlight_text: 'High dietary fiber content', display_order: 3 },
        // Besan Ladoo Cookies
        { product_id: insertedProducts[3].id, highlight_text: '100% gluten-free', display_order: 1 },
        { product_id: insertedProducts[3].id, highlight_text: 'Traditional ladoo taste', display_order: 2 },
        { product_id: insertedProducts[3].id, highlight_text: 'Made with pure ghee', display_order: 3 },
        { product_id: insertedProducts[3].id, highlight_text: 'Rich in plant protein', display_order: 4 },
        // Jowar Coconut Muffins
        { product_id: insertedProducts[4].id, highlight_text: 'Gluten-free jowar flour', display_order: 1 },
        { product_id: insertedProducts[4].id, highlight_text: 'Fresh coconut goodness', display_order: 2 },
        { product_id: insertedProducts[4].id, highlight_text: 'Jaggery sweetened', display_order: 3 },
        // Date & Walnut Cake Bars
        { product_id: insertedProducts[5].id, highlight_text: 'No added refined sugar', display_order: 1 },
        { product_id: insertedProducts[5].id, highlight_text: 'Rich in omega-3 fatty acids', display_order: 2 },
        { product_id: insertedProducts[5].id, highlight_text: 'Natural energy booster', display_order: 3 },
        { product_id: insertedProducts[5].id, highlight_text: 'On-the-go snack', display_order: 4 },
        // Almond Flour Nankhatai
        { product_id: insertedProducts[6].id, highlight_text: 'Keto-friendly option', display_order: 1 },
        { product_id: insertedProducts[6].id, highlight_text: 'High in protein and healthy fats', display_order: 2 },
        { product_id: insertedProducts[6].id, highlight_text: 'Traditional Indian taste', display_order: 3 },
        // Whole Wheat Til Cookies
        { product_id: insertedProducts[7].id, highlight_text: 'Calcium-rich sesame seeds', display_order: 1 },
        { product_id: insertedProducts[7].id, highlight_text: '100% whole wheat', display_order: 2 },
        { product_id: insertedProducts[7].id, highlight_text: 'Supports bone health', display_order: 3 },
        { product_id: insertedProducts[7].id, highlight_text: 'Iron-rich ingredients', display_order: 4 },
        // Ragi Finger Millet Sticks
        { product_id: insertedProducts[8].id, highlight_text: 'Superfood ragi base', display_order: 1 },
        { product_id: insertedProducts[8].id, highlight_text: 'Boosts hemoglobin naturally', display_order: 2 },
        { product_id: insertedProducts[8].id, highlight_text: 'Rich in calcium', display_order: 3 },
        // Bajra Masala Crackers
        { product_id: insertedProducts[9].id, highlight_text: 'Gluten-free pearl millet', display_order: 1 },
        { product_id: insertedProducts[9].id, highlight_text: 'Authentic Indian spices', display_order: 2 },
        { product_id: insertedProducts[9].id, highlight_text: 'High in magnesium', display_order: 3 },
        { product_id: insertedProducts[9].id, highlight_text: 'Perfect with dips', display_order: 4 },
        // Quinoa Puff Energy Balls
        { product_id: insertedProducts[10].id, highlight_text: 'Complete protein source', display_order: 1 },
        { product_id: insertedProducts[10].id, highlight_text: 'Pre-workout energy booster', display_order: 2 },
        { product_id: insertedProducts[10].id, highlight_text: 'Natural date sweetness', display_order: 3 },
        // Amaranth Chikki Bars
        { product_id: insertedProducts[11].id, highlight_text: 'Ancient grain superfood', display_order: 1 },
        { product_id: insertedProducts[11].id, highlight_text: 'Traditional jaggery base', display_order: 2 },
        { product_id: insertedProducts[11].id, highlight_text: 'High in iron and calcium', display_order: 3 },
        { product_id: insertedProducts[11].id, highlight_text: 'Authentic Indian taste', display_order: 4 },
        // Multi-Millet Namkeen Mix
        { product_id: insertedProducts[12].id, highlight_text: 'Blend of three millets', display_order: 1 },
        { product_id: insertedProducts[12].id, highlight_text: 'High fiber content', display_order: 2 },
        { product_id: insertedProducts[12].id, highlight_text: 'Supports digestion', display_order: 3 },
        // Ragi Chakli Spirals
        { product_id: insertedProducts[13].id, highlight_text: 'Authentic South Indian recipe', display_order: 1 },
        { product_id: insertedProducts[13].id, highlight_text: 'Gluten-free alternative', display_order: 2 },
        { product_id: insertedProducts[13].id, highlight_text: 'Festival-ready snack', display_order: 3 },
        { product_id: insertedProducts[13].id, highlight_text: 'Ragi nutritional benefits', display_order: 4 },
        // Jowar Puffs Bhel Mix
        { product_id: insertedProducts[14].id, highlight_text: 'Low calorie snacking', display_order: 1 },
        { product_id: insertedProducts[14].id, highlight_text: 'Low in sugar', display_order: 2 },
        { product_id: insertedProducts[14].id, highlight_text: 'Light and airy texture', display_order: 3 },
        // Bajra Methi Khakhra
        { product_id: insertedProducts[15].id, highlight_text: 'Traditional Gujarati recipe', display_order: 1 },
        { product_id: insertedProducts[15].id, highlight_text: 'Fresh fenugreek leaves', display_order: 2 },
        { product_id: insertedProducts[15].id, highlight_text: 'Regulates blood sugar', display_order: 3 },
        { product_id: insertedProducts[15].id, highlight_text: 'High in fiber', display_order: 4 },
        // Coconut Dates Energy Bars
        { product_id: insertedProducts[16].id, highlight_text: '100% plant-based', display_order: 1 },
        { product_id: insertedProducts[16].id, highlight_text: 'Rich in MCT fatty acids', display_order: 2 },
        { product_id: insertedProducts[16].id, highlight_text: 'Instant energy source', display_order: 3 },
        // Cashew Cranberry Bites
        { product_id: insertedProducts[17].id, highlight_text: 'Vegan-friendly snack', display_order: 1 },
        { product_id: insertedProducts[17].id, highlight_text: 'Rich in antioxidants', display_order: 2 },
        { product_id: insertedProducts[17].id, highlight_text: 'Heart-healthy fats', display_order: 3 },
        { product_id: insertedProducts[17].id, highlight_text: 'Sweet and tangy flavor', display_order: 4 },
        // Peanut Jaggery Chikki
        { product_id: insertedProducts[18].id, highlight_text: 'Traditional Indian brittle', display_order: 1 },
        { product_id: insertedProducts[18].id, highlight_text: 'Organic jaggery sweetened', display_order: 2 },
        { product_id: insertedProducts[18].id, highlight_text: 'Iron-rich ingredients', display_order: 3 },
        // Dry Fruit Ladoo Mix
        { product_id: insertedProducts[19].id, highlight_text: 'Dairy-free nutrition', display_order: 1 },
        { product_id: insertedProducts[19].id, highlight_text: 'Blend of premium nuts', display_order: 2 },
        { product_id: insertedProducts[19].id, highlight_text: 'Rich in omega-3s', display_order: 3 },
        { product_id: insertedProducts[19].id, highlight_text: 'Traditional ladoo taste', display_order: 4 },
        // Mini Ragi Chocolate Cookies
        { product_id: insertedProducts[20].id, highlight_text: 'Kid-friendly portions', display_order: 1 },
        { product_id: insertedProducts[20].id, highlight_text: 'Natural cocoa flavor', display_order: 2 },
        { product_id: insertedProducts[20].id, highlight_text: 'Calcium for growing bones', display_order: 3 },
        // Honey Oats Granola Bars
        { product_id: insertedProducts[21].id, highlight_text: 'Perfect for lunchboxes', display_order: 1 },
        { product_id: insertedProducts[21].id, highlight_text: 'Pure honey sweetened', display_order: 2 },
        { product_id: insertedProducts[21].id, highlight_text: 'Sustained energy release', display_order: 3 },
        { product_id: insertedProducts[21].id, highlight_text: 'Protein-rich snack', display_order: 4 },
        // Fruit & Nut Trail Mix
        { product_id: insertedProducts[22].id, highlight_text: 'Brain development support', display_order: 1 },
        { product_id: insertedProducts[22].id, highlight_text: 'Colorful and fun', display_order: 2 },
        { product_id: insertedProducts[22].id, highlight_text: 'Essential nutrients blend', display_order: 3 },
        // Turmeric Jaggery Pops
        { product_id: insertedProducts[23].id, highlight_text: 'Immunity boosting', display_order: 1 },
        { product_id: insertedProducts[23].id, highlight_text: 'Ayurvedic benefits', display_order: 2 },
        { product_id: insertedProducts[23].id, highlight_text: 'Natural anti-inflammatory', display_order: 3 },
        { product_id: insertedProducts[23].id, highlight_text: 'Golden goodness', display_order: 4 },
    ];

    await db.insert(productHighlights).values(highlightsData.map(h => ({ ...h, created_at: new Date() })));
    console.log(`✅ Inserted ${highlightsData.length} product highlights`);

    const ingredientsData = [
        // Ragi Chocolate Walnut Brownies
        { product_id: insertedProducts[0].id, ingredient_name: 'Ragi flour (finger millet)', display_order: 1 },
        { product_id: insertedProducts[0].id, ingredient_name: 'Pure cocoa powder', display_order: 2 },
        { product_id: insertedProducts[0].id, ingredient_name: 'Walnuts', display_order: 3 },
        { product_id: insertedProducts[0].id, ingredient_name: 'Dates paste', display_order: 4 },
        { product_id: insertedProducts[0].id, ingredient_name: 'Coconut oil', display_order: 5 },
        { product_id: insertedProducts[0].id, ingredient_name: 'Baking powder', display_order: 6 },
        // Quinoa Banana Bread
        { product_id: insertedProducts[1].id, ingredient_name: 'Quinoa flour', display_order: 1 },
        { product_id: insertedProducts[1].id, ingredient_name: 'Ripe bananas', display_order: 2 },
        { product_id: insertedProducts[1].id, ingredient_name: 'Whole wheat flour', display_order: 3 },
        { product_id: insertedProducts[1].id, ingredient_name: 'Jaggery', display_order: 4 },
        { product_id: insertedProducts[1].id, ingredient_name: 'Coconut oil', display_order: 5 },
        // Multigrain Digestive Cookies
        { product_id: insertedProducts[2].id, ingredient_name: 'Whole wheat flour', display_order: 1 },
        { product_id: insertedProducts[2].id, ingredient_name: 'Rolled oats', display_order: 2 },
        { product_id: insertedProducts[2].id, ingredient_name: 'Ragi flour', display_order: 3 },
        { product_id: insertedProducts[2].id, ingredient_name: 'Jaggery', display_order: 4 },
        { product_id: insertedProducts[2].id, ingredient_name: 'Ghee', display_order: 5 },
        { product_id: insertedProducts[2].id, ingredient_name: 'Cardamom powder', display_order: 6 },
        // Besan Ladoo Cookies
        { product_id: insertedProducts[3].id, ingredient_name: 'Besan (chickpea flour)', display_order: 1 },
        { product_id: insertedProducts[3].id, ingredient_name: 'Pure ghee', display_order: 2 },
        { product_id: insertedProducts[3].id, ingredient_name: 'Powdered jaggery', display_order: 3 },
        { product_id: insertedProducts[3].id, ingredient_name: 'Cardamom', display_order: 4 },
        { product_id: insertedProducts[3].id, ingredient_name: 'Almonds', display_order: 5 },
        // Jowar Coconut Muffins
        { product_id: insertedProducts[4].id, ingredient_name: 'Jowar flour (sorghum)', display_order: 1 },
        { product_id: insertedProducts[4].id, ingredient_name: 'Fresh grated coconut', display_order: 2 },
        { product_id: insertedProducts[4].id, ingredient_name: 'Jaggery', display_order: 3 },
        { product_id: insertedProducts[4].id, ingredient_name: 'Coconut oil', display_order: 4 },
        { product_id: insertedProducts[4].id, ingredient_name: 'Baking soda', display_order: 5 },
        // Date & Walnut Cake Bars
        { product_id: insertedProducts[5].id, ingredient_name: 'Medjool dates', display_order: 1 },
        { product_id: insertedProducts[5].id, ingredient_name: 'Walnuts', display_order: 2 },
        { product_id: insertedProducts[5].id, ingredient_name: 'Whole wheat flour', display_order: 3 },
        { product_id: insertedProducts[5].id, ingredient_name: 'Almond flour', display_order: 4 },
        { product_id: insertedProducts[5].id, ingredient_name: 'Coconut oil', display_order: 5 },
        { product_id: insertedProducts[5].id, ingredient_name: 'Vanilla extract', display_order: 6 },
        // Almond Flour Nankhatai
        { product_id: insertedProducts[6].id, ingredient_name: 'Almond flour', display_order: 1 },
        { product_id: insertedProducts[6].id, ingredient_name: 'Pure ghee', display_order: 2 },
        { product_id: insertedProducts[6].id, ingredient_name: 'Powdered jaggery', display_order: 3 },
        { product_id: insertedProducts[6].id, ingredient_name: 'Cardamom', display_order: 4 },
        { product_id: insertedProducts[6].id, ingredient_name: 'Saffron strands', display_order: 5 },
        // Whole Wheat Til Cookies
        { product_id: insertedProducts[7].id, ingredient_name: 'Whole wheat flour', display_order: 1 },
        { product_id: insertedProducts[7].id, ingredient_name: 'Roasted sesame seeds', display_order: 2 },
        { product_id: insertedProducts[7].id, ingredient_name: 'Jaggery', display_order: 3 },
        { product_id: insertedProducts[7].id, ingredient_name: 'Ghee', display_order: 4 },
        { product_id: insertedProducts[7].id, ingredient_name: 'Cardamom', display_order: 5 },
        // Ragi Finger Millet Sticks
        { product_id: insertedProducts[8].id, ingredient_name: 'Ragi flour', display_order: 1 },
        { product_id: insertedProducts[8].id, ingredient_name: 'Ajwain seeds', display_order: 2 },
        { product_id: insertedProducts[8].id, ingredient_name: 'Cumin seeds', display_order: 3 },
        { product_id: insertedProducts[8].id, ingredient_name: 'Red chili powder', display_order: 4 },
        { product_id: insertedProducts[8].id, ingredient_name: 'Rock salt', display_order: 5 },
        // Bajra Masala Crackers
        { product_id: insertedProducts[9].id, ingredient_name: 'Bajra flour (pearl millet)', display_order: 1 },
        { product_id: insertedProducts[9].id, ingredient_name: 'Garam masala', display_order: 2 },
        { product_id: insertedProducts[9].id, ingredient_name: 'Turmeric powder', display_order: 3 },
        { product_id: insertedProducts[9].id, ingredient_name: 'Sesame seeds', display_order: 4 },
        { product_id: insertedProducts[9].id, ingredient_name: 'Cold-pressed oil', display_order: 5 },
        { product_id: insertedProducts[9].id, ingredient_name: 'Rock salt', display_order: 6 },
        // Quinoa Puff Energy Balls
        { product_id: insertedProducts[10].id, ingredient_name: 'Puffed quinoa', display_order: 1 },
        { product_id: insertedProducts[10].id, ingredient_name: 'Dates', display_order: 2 },
        { product_id: insertedProducts[10].id, ingredient_name: 'Almonds', display_order: 3 },
        { product_id: insertedProducts[10].id, ingredient_name: 'Cashews', display_order: 4 },
        { product_id: insertedProducts[10].id, ingredient_name: 'Honey', display_order: 5 },
        // Amaranth Chikki Bars
        { product_id: insertedProducts[11].id, ingredient_name: 'Amaranth seeds', display_order: 1 },
        { product_id: insertedProducts[11].id, ingredient_name: 'Organic jaggery', display_order: 2 },
        { product_id: insertedProducts[11].id, ingredient_name: 'Peanuts', display_order: 3 },
        { product_id: insertedProducts[11].id, ingredient_name: 'Sesame seeds', display_order: 4 },
        { product_id: insertedProducts[11].id, ingredient_name: 'Ghee', display_order: 5 },
        // Multi-Millet Namkeen Mix
        { product_id: insertedProducts[12].id, ingredient_name: 'Bajra flour', display_order: 1 },
        { product_id: insertedProducts[12].id, ingredient_name: 'Jowar flour', display_order: 2 },
        { product_id: insertedProducts[12].id, ingredient_name: 'Ragi flour', display_order: 3 },
        { product_id: insertedProducts[12].id, ingredient_name: 'Roasted peanuts', display_order: 4 },
        { product_id: insertedProducts[12].id, ingredient_name: 'Curry leaves', display_order: 5 },
        { product_id: insertedProducts[12].id, ingredient_name: 'Spice mix', display_order: 6 },
        // Ragi Chakli Spirals
        { product_id: insertedProducts[13].id, ingredient_name: 'Ragi flour', display_order: 1 },
        { product_id: insertedProducts[13].id, ingredient_name: 'Rice flour', display_order: 2 },
        { product_id: insertedProducts[13].id, ingredient_name: 'Sesame seeds', display_order: 3 },
        { product_id: insertedProducts[13].id, ingredient_name: 'Cumin seeds', display_order: 4 },
        { product_id: insertedProducts[13].id, ingredient_name: 'Asafoetida', display_order: 5 },
        // Jowar Puffs Bhel Mix
        { product_id: insertedProducts[14].id, ingredient_name: 'Puffed jowar', display_order: 1 },
        { product_id: insertedProducts[14].id, ingredient_name: 'Roasted peanuts', display_order: 2 },
        { product_id: insertedProducts[14].id, ingredient_name: 'Curry leaves', display_order: 3 },
        { product_id: insertedProducts[14].id, ingredient_name: 'Mustard seeds', display_order: 4 },
        { product_id: insertedProducts[14].id, ingredient_name: 'Turmeric', display_order: 5 },
        // Bajra Methi Khakhra
        { product_id: insertedProducts[15].id, ingredient_name: 'Bajra flour', display_order: 1 },
        { product_id: insertedProducts[15].id, ingredient_name: 'Fresh fenugreek leaves', display_order: 2 },
        { product_id: insertedProducts[15].id, ingredient_name: 'Whole wheat flour', display_order: 3 },
        { product_id: insertedProducts[15].id, ingredient_name: 'Cumin seeds', display_order: 4 },
        { product_id: insertedProducts[15].id, ingredient_name: 'Cold-pressed oil', display_order: 5 },
        { product_id: insertedProducts[15].id, ingredient_name: 'Rock salt', display_order: 6 },
        // Coconut Dates Energy Bars
        { product_id: insertedProducts[16].id, ingredient_name: 'Fresh coconut', display_order: 1 },
        { product_id: insertedProducts[16].id, ingredient_name: 'Medjool dates', display_order: 2 },
        { product_id: insertedProducts[16].id, ingredient_name: 'Almonds', display_order: 3 },
        { product_id: insertedProducts[16].id, ingredient_name: 'Cashews', display_order: 4 },
        { product_id: insertedProducts[16].id, ingredient_name: 'Coconut oil', display_order: 5 },
        // Cashew Cranberry Bites
        { product_id: insertedProducts[17].id, ingredient_name: 'Roasted cashews', display_order: 1 },
        { product_id: insertedProducts[17].id, ingredient_name: 'Dried cranberries', display_order: 2 },
        { product_id: insertedProducts[17].id, ingredient_name: 'Dates', display_order: 3 },
        { product_id: insertedProducts[17].id, ingredient_name: 'Chia seeds', display_order: 4 },
        { product_id: insertedProducts[17].id, ingredient_name: 'Vanilla extract', display_order: 5 },
        // Peanut Jaggery Chikki
        { product_id: insertedProducts[18].id, ingredient_name: 'Roasted peanuts', display_order: 1 },
        { product_id: insertedProducts[18].id, ingredient_name: 'Organic jaggery', display_order: 2 },
        { product_id: insertedProducts[18].id, ingredient_name: 'Ghee', display_order: 3 },
        { product_id: insertedProducts[18].id, ingredient_name: 'Cardamom', display_order: 4 },
        // Dry Fruit Ladoo Mix
        { product_id: insertedProducts[19].id, ingredient_name: 'Almonds', display_order: 1 },
        { product_id: insertedProducts[19].id, ingredient_name: 'Cashews', display_order: 2 },
        { product_id: insertedProducts[19].id, ingredient_name: 'Pistachios', display_order: 3 },
        { product_id: insertedProducts[19].id, ingredient_name: 'Dates', display_order: 4 },
        { product_id: insertedProducts[19].id, ingredient_name: 'Raisins', display_order: 5 },
        { product_id: insertedProducts[19].id, ingredient_name: 'Cardamom', display_order: 6 },
        // Mini Ragi Chocolate Cookies
        { product_id: insertedProducts[20].id, ingredient_name: 'Ragi flour', display_order: 1 },
        { product_id: insertedProducts[20].id, ingredient_name: 'Natural cocoa', display_order: 2 },
        { product_id: insertedProducts[20].id, ingredient_name: 'Jaggery', display_order: 3 },
        { product_id: insertedProducts[20].id, ingredient_name: 'Coconut oil', display_order: 4 },
        { product_id: insertedProducts[20].id, ingredient_name: 'Vanilla', display_order: 5 },
        // Honey Oats Granola Bars
        { product_id: insertedProducts[21].id, ingredient_name: 'Rolled oats', display_order: 1 },
        { product_id: insertedProducts[21].id, ingredient_name: 'Pure honey', display_order: 2 },
        { product_id: insertedProducts[21].id, ingredient_name: 'Almonds', display_order: 3 },
        { product_id: insertedProducts[21].id, ingredient_name: 'Pumpkin seeds', display_order: 4 },
        { product_id: insertedProducts[21].id, ingredient_name: 'Sunflower seeds', display_order: 5 },
        // Fruit & Nut Trail Mix
        { product_id: insertedProducts[22].id, ingredient_name: 'Dried mango pieces', display_order: 1 },
        { product_id: insertedProducts[22].id, ingredient_name: 'Raisins', display_order: 2 },
        { product_id: insertedProducts[22].id, ingredient_name: 'Cashews', display_order: 3 },
        { product_id: insertedProducts[22].id, ingredient_name: 'Almonds', display_order: 4 },
        { product_id: insertedProducts[22].id, ingredient_name: 'Pumpkin seeds', display_order: 5 },
        { product_id: insertedProducts[22].id, ingredient_name: 'Sunflower seeds', display_order: 6 },
        // Turmeric Jaggery Pops
        { product_id: insertedProducts[23].id, ingredient_name: 'Organic turmeric', display_order: 1 },
        { product_id: insertedProducts[23].id, ingredient_name: 'Jaggery', display_order: 2 },
        { product_id: insertedProducts[23].id, ingredient_name: 'Ghee', display_order: 3 },
        { product_id: insertedProducts[23].id, ingredient_name: 'Black pepper', display_order: 4 },
        { product_id: insertedProducts[23].id, ingredient_name: 'Cardamom', display_order: 5 },
    ];

    await db.insert(productIngredients).values(ingredientsData.map(i => ({ ...i, created_at: new Date() })));
    console.log(`✅ Inserted ${ingredientsData.length} product ingredients`);

    console.log('✅ Successfully seeded 24 new Indian healthy snack products with all related data!');
    console.log(`📊 Total records created:
    - Products: ${insertedProducts.length}
    - Images: ${productImagesData.length}
    - Nutrition: ${nutritionData.length}
    - Highlights: ${highlightsData.length}
    - Ingredients: ${ingredientsData.length}`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});