import { db } from '@/db';
import { products, productImages, productNutrition, productIngredients, productHighlights } from '@/db/schema';

async function main() {
    const newProducts = [
        // Health-Focused Bakery (8 products)
        {
            name: 'Ragi Chocolate Walnut Brownies',
            slug: 'ragi-chocolate-walnut-brownies',
            category: 'bakery',
            subCategory: 'low-sugar',
            description: 'Decadent brownies made with ragi flour and rich dark chocolate. Sweetened with dates and loaded with crunchy walnuts for a guilt-free indulgence.',
            badge: 'Bestseller',
            featured: true,
            rating: 4.8,
            reviews: 187,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Quinoa Banana Bread',
            slug: 'quinoa-banana-bread',
            category: 'bakery',
            subCategory: 'protein-rich',
            description: 'Moist and nutritious banana bread enriched with protein-packed quinoa. Perfect for breakfast or as a healthy snack throughout the day.',
            badge: null,
            featured: false,
            rating: 4.6,
            reviews: 142,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Multigrain Digestive Cookies',
            slug: 'multigrain-digestive-cookies',
            category: 'bakery',
            subCategory: 'high-fiber',
            description: 'Crunchy digestive cookies made with a blend of five ancient grains. High in fiber and perfect for aiding digestion with your evening tea.',
            badge: 'New Arrival',
            featured: true,
            rating: 4.7,
            reviews: 98,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Besan Ladoo Cookies',
            slug: 'besan-ladoo-cookies',
            category: 'bakery',
            subCategory: 'gluten-free',
            description: 'Traditional besan ladoo flavor in a convenient cookie form. Made with pure ghee and cardamom, these gluten-free treats bring back nostalgic memories.',
            badge: null,
            featured: false,
            rating: 4.5,
            reviews: 156,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Jowar Coconut Muffins',
            slug: 'jowar-coconut-muffins',
            category: 'bakery',
            subCategory: 'gluten-free',
            description: 'Light and fluffy muffins made with jowar flour and fresh coconut. Naturally gluten-free and perfect for a quick breakfast on busy mornings.',
            badge: 'Low Cal',
            featured: false,
            rating: 4.4,
            reviews: 78,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Date & Walnut Cake Bars',
            slug: 'date-walnut-cake-bars',
            category: 'bakery',
            subCategory: 'low-sugar',
            description: 'Rich cake bars naturally sweetened with dates and studded with crunchy walnuts. No refined sugar added, just wholesome goodness in every bite.',
            badge: null,
            featured: false,
            rating: 4.6,
            reviews: 134,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Almond Flour Nankhatai',
            slug: 'almond-flour-nankhatai',
            category: 'bakery',
            subCategory: 'protein-rich',
            description: 'Classic Indian shortbread cookies reimagined with almond flour for extra protein. Flavored with cardamom and garnished with slivered almonds.',
            badge: 'Bestseller',
            featured: true,
            rating: 4.9,
            reviews: 223,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Whole Wheat Til Cookies',
            slug: 'whole-wheat-til-cookies',
            category: 'bakery',
            subCategory: 'high-fiber',
            description: 'Nutty sesame cookies made with stone-ground whole wheat flour. Rich in calcium and fiber, these traditional cookies are perfect with hot beverages.',
            badge: null,
            featured: false,
            rating: 4.5,
            reviews: 91,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Ancient Grains Collection (8 products)
        {
            name: 'Ragi Finger Millet Sticks',
            slug: 'ragi-finger-millet-sticks',
            category: 'ancient-grains',
            subCategory: 'superfood',
            description: 'Crispy ragi sticks packed with calcium and iron. These nutrient-dense snacks are perfect for growing children and health-conscious adults alike.',
            badge: 'Superfood',
            featured: true,
            rating: 4.7,
            reviews: 167,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Bajra Masala Crackers',
            slug: 'bajra-masala-crackers',
            category: 'ancient-grains',
            subCategory: 'gluten-free',
            description: 'Savory pearl millet crackers seasoned with aromatic Indian spices. Gluten-free and diabetic-friendly, perfect for guilt-free snacking.',
            badge: null,
            featured: false,
            rating: 4.6,
            reviews: 124,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Quinoa Puff Energy Balls',
            slug: 'quinoa-puff-energy-balls',
            category: 'ancient-grains',
            subCategory: 'protein-rich',
            description: 'Protein-packed energy balls made with puffed quinoa, dates, and mixed nuts. Perfect pre-workout snack or midday energy boost.',
            badge: 'High Protein',
            featured: true,
            rating: 4.8,
            reviews: 201,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Amaranth Chikki Bars',
            slug: 'amaranth-chikki-bars',
            category: 'ancient-grains',
            subCategory: 'superfood',
            description: 'Traditional chikki elevated with amaranth seeds and jaggery. Rich in protein and minerals, this ancient superfood makes for a perfect healthy dessert.',
            badge: null,
            featured: false,
            rating: 4.5,
            reviews: 87,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Multi-Millet Namkeen Mix',
            slug: 'multi-millet-namkeen-mix',
            category: 'ancient-grains',
            subCategory: 'high-fiber',
            description: 'Crunchy namkeen mix featuring five different millets. High in fiber and essential minerals, this savory snack is perfect for evening tea time.',
            badge: 'New Arrival',
            featured: false,
            rating: 4.4,
            reviews: 112,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Ragi Chakli Spirals',
            slug: 'ragi-chakli-spirals',
            category: 'ancient-grains',
            subCategory: 'gluten-free',
            description: 'Traditional spiral chaklis made with calcium-rich ragi flour. Seasoned with cumin and sesame, these gluten-free treats are perfect for festive occasions.',
            badge: null,
            featured: false,
            rating: 4.7,
            reviews: 145,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Jowar Puffs Bhel Mix',
            slug: 'jowar-puffs-bhel-mix',
            category: 'ancient-grains',
            subCategory: 'low-sugar',
            description: 'Light and airy jowar puffs mixed with roasted peanuts and spices. A healthier take on traditional bhel that is low in calories and high in taste.',
            badge: 'Low Cal',
            featured: false,
            rating: 4.3,
            reviews: 76,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Bajra Methi Khakhra',
            slug: 'bajra-methi-khakhra',
            category: 'ancient-grains',
            subCategory: 'high-fiber',
            description: 'Crispy thin khakhras made with pearl millet and fresh fenugreek leaves. High in fiber and perfect for controlling blood sugar levels.',
            badge: null,
            featured: false,
            rating: 4.6,
            reviews: 103,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Vegan Options (4 products)
        {
            name: 'Coconut Dates Energy Bars',
            slug: 'coconut-dates-energy-bars',
            category: 'vegan',
            subCategory: 'vegan',
            description: 'No-bake energy bars made with fresh coconut and Medjool dates. 100% plant-based with no added sugars, perfect for sustained energy throughout the day.',
            badge: 'Bestseller',
            featured: true,
            rating: 4.8,
            reviews: 189,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Cashew Cranberry Bites',
            slug: 'cashew-cranberry-bites',
            category: 'vegan',
            subCategory: 'vegan',
            description: 'Delicious bite-sized treats made with roasted cashews and dried cranberries. Dairy-free and naturally sweet, these are perfect for guilt-free snacking.',
            badge: null,
            featured: false,
            rating: 4.6,
            reviews: 127,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Peanut Jaggery Chikki',
            slug: 'peanut-jaggery-chikki',
            category: 'vegan',
            subCategory: 'vegan',
            description: 'Classic Indian chikki made with roasted peanuts and organic jaggery. Completely vegan and packed with protein and iron for healthy living.',
            badge: null,
            featured: false,
            rating: 4.5,
            reviews: 156,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Dry Fruit Ladoo Mix',
            slug: 'dry-fruit-ladoo-mix',
            category: 'vegan',
            subCategory: 'vegan',
            description: 'Luxurious ladoos made with premium dry fruits, dates, and coconut. No dairy or refined sugars, just pure plant-based nutrition and traditional taste.',
            badge: 'New Arrival',
            featured: false,
            rating: 4.7,
            reviews: 94,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        // Kids' Healthy Treats (4 products)
        {
            name: 'Mini Ragi Chocolate Cookies',
            slug: 'mini-ragi-chocolate-cookies',
            category: 'kids',
            subCategory: 'low-sugar',
            description: 'Fun-sized chocolate cookies made with ragi flour and real cocoa. Low in sugar but high in calcium, these are perfect for growing kids.',
            badge: 'Bestseller',
            featured: false,
            rating: 4.9,
            reviews: 234,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Honey Oats Granola Bars',
            slug: 'honey-oats-granola-bars',
            category: 'kids',
            subCategory: 'protein-rich',
            description: 'Crunchy granola bars sweetened with pure honey and packed with oats. High in protein and fiber, perfect for school lunch boxes.',
            badge: null,
            featured: false,
            rating: 4.6,
            reviews: 178,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Fruit & Nut Trail Mix',
            slug: 'fruit-nut-trail-mix',
            category: 'kids',
            subCategory: 'superfood',
            description: 'Colorful mix of dried fruits, nuts, and seeds. Superfood blend that provides essential vitamins and minerals for active children.',
            badge: 'Superfood',
            featured: false,
            rating: 4.7,
            reviews: 143,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Turmeric Jaggery Pops',
            slug: 'turmeric-jaggery-pops',
            category: 'kids',
            subCategory: 'superfood',
            description: 'Immunity-boosting pops made with turmeric and jaggery. Fun to eat and packed with natural anti-inflammatory properties for growing kids.',
            badge: 'New Arrival',
            featured: false,
            rating: 4.4,
            reviews: 89,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];

    const insertedProducts = await db.insert(products).values(newProducts).returning();

    const productImagesData = insertedProducts.map((product) => ({
        productId: product.id,
        imageUrl: `https://qcvhocsgjohxpwbhfvyf.supabase.co/storage/v1/object/public/products/${product.slug}-1.jpg`,
        altText: `${product.name} - Healthy Indian snack`,
        displayOrder: 1,
        isPrimary: true,
        createdAt: new Date(),
    }));

    await db.insert(productImages).values(productImagesData);

    const nutritionData = [
        { servingSize: '3 pieces (50g)', calories: 185, protein: 5.2, carbs: 24.5, fat: 8.5, fiber: 4.2, sugar: 8.5 },
        { servingSize: '1 slice (60g)', calories: 210, protein: 6.8, carbs: 32.0, fat: 7.2, fiber: 5.5, sugar: 12.0 },
        { servingSize: '4 cookies (40g)', calories: 165, protein: 4.5, carbs: 28.0, fat: 5.8, fiber: 6.2, sugar: 6.0 },
        { servingSize: '3 cookies (45g)', calories: 195, protein: 7.2, carbs: 22.5, fat: 9.8, fiber: 3.8, sugar: 9.5 },
        { servingSize: '1 muffin (55g)', calories: 175, protein: 4.8, carbs: 26.0, fat: 6.5, fiber: 4.5, sugar: 8.0 },
        { servingSize: '1 bar (50g)', calories: 220, protein: 6.5, carbs: 31.0, fat: 9.2, fiber: 5.8, sugar: 14.5 },
        { servingSize: '3 pieces (35g)', calories: 180, protein: 8.5, carbs: 18.0, fat: 10.5, fiber: 4.2, sugar: 7.0 },
        { servingSize: '4 cookies (40g)', calories: 170, protein: 5.8, carbs: 25.0, fat: 6.5, fiber: 6.8, sugar: 5.5 },
        { servingSize: '25g serving', calories: 125, protein: 4.2, carbs: 18.5, fat: 4.8, fiber: 5.2, sugar: 3.5 },
        { servingSize: '30g serving', calories: 140, protein: 4.5, carbs: 22.0, fat: 5.2, fiber: 5.8, sugar: 2.8 },
        { servingSize: '3 balls (45g)', calories: 205, protein: 9.5, carbs: 24.0, fat: 8.8, fiber: 4.5, sugar: 11.0 },
        { servingSize: '1 bar (40g)', calories: 175, protein: 8.2, carbs: 26.5, fat: 5.5, fiber: 4.8, sugar: 12.5 },
        { servingSize: '30g serving', calories: 145, protein: 5.8, carbs: 20.5, fat: 5.8, fiber: 6.5, sugar: 3.2 },
        { servingSize: '25g serving', calories: 120, protein: 4.8, carbs: 17.5, fat: 4.5, fiber: 5.5, sugar: 2.5 },
        { servingSize: '30g serving', calories: 135, protein: 4.2, carbs: 19.0, fat: 5.5, fiber: 5.2, sugar: 2.0 },
        { servingSize: '2 pieces (35g)', calories: 155, protein: 5.5, carbs: 24.0, fat: 5.2, fiber: 6.8, sugar: 3.5 },
        { servingSize: '1 bar (50g)', calories: 235, protein: 7.5, carbs: 35.0, fat: 9.2, fiber: 6.2, sugar: 15.5 },
        { servingSize: '5 pieces (40g)', calories: 195, protein: 8.8, carbs: 22.5, fat: 9.8, fiber: 4.8, sugar: 10.0 },
        { servingSize: '1 bar (45g)', calories: 190, protein: 6.5, carbs: 28.0, fat: 7.5, fiber: 4.5, sugar: 13.0 },
        { servingSize: '3 pieces (50g)', calories: 225, protein: 9.2, carbs: 31.5, fat: 9.5, fiber: 5.2, sugar: 14.5 },
        { servingSize: '5 cookies (35g)', calories: 155, protein: 5.2, carbs: 20.0, fat: 7.2, fiber: 4.8, sugar: 6.5 },
        { servingSize: '1 bar (45g)', calories: 185, protein: 6.8, carbs: 28.5, fat: 6.5, fiber: 5.5, sugar: 10.5 },
        { servingSize: '30g serving', calories: 145, protein: 5.5, carbs: 20.0, fat: 6.2, fiber: 4.2, sugar: 8.5 },
        { servingSize: '4 pieces (30g)', calories: 135, protein: 4.5, carbs: 22.0, fat: 4.5, fiber: 4.5, sugar: 9.0 },
    ];

    const productNutritionData = insertedProducts.map((product, index) => ({
        productId: product.id,
        ...nutritionData[index],
        createdAt: new Date(),
    }));

    await db.insert(productNutrition).values(productNutritionData);

    const highlightsData = [
        ['Rich in Calcium from Ragi', 'No Refined Sugar', 'Omega-3 from Walnuts', 'Heart Healthy'],
        ['Complete Protein Source', 'Natural Sweetness from Banana', 'Gluten-Free Option', 'Sustained Energy'],
        ['High Fiber Content', 'Aids Digestion', 'Five Ancient Grains', 'No Maida'],
        ['Gluten-Free Goodness', 'Traditional Flavor', 'Pure Ghee Used', 'No Artificial Flavors'],
        ['Naturally Gluten-Free', 'Low Calorie Snack', 'Fresh Coconut Used', 'Rich in Magnesium'],
        ['No Refined Sugar', 'Natural Iron Source', 'Omega-3 Rich', 'Diabetic Friendly'],
        ['High Protein Content', 'Almond Flour Base', 'Traditional Recipe', 'Low Carb Option'],
        ['Rich in Calcium', 'Stone Ground Flour', 'High Fiber', 'Traditional Indian Cookie'],
        ['Calcium Powerhouse', 'Natural Iron Source', 'Gluten-Free Snack', 'Immunity Boosting'],
        ['Diabetic Friendly', 'Gluten-Free Goodness', 'Rich in Minerals', 'Heart Healthy'],
        ['Complete Protein', 'Pre-Workout Snack', 'No Added Sugar', 'Sustained Energy Release'],
        ['Ancient Superfood', 'Rich in Lysine', 'Jaggery Sweetened', 'No Refined Sugar'],
        ['Five Millet Blend', 'High Fiber Content', 'Rich in Minerals', 'Traditional Taste'],
        ['Calcium Rich Ragi', 'Gluten-Free Treat', 'Traditional Recipe', 'Festive Favorite'],
        ['Low Calorie Snack', 'Diabetic Friendly', 'Light & Airy', 'High in Fiber'],
        ['Blood Sugar Control', 'Fenugreek Benefits', 'High Fiber', 'Traditional Khakhra'],
        ['100% Plant-Based', 'No Added Sugar', 'Natural Energy Boost', 'Vegan Friendly'],
        ['Dairy-Free Delight', 'Antioxidant Rich', 'Vegan Snack', 'No Refined Sugar'],
        ['Rich in Protein', 'Natural Iron Source', 'Vegan Treat', 'Jaggery Sweetened'],
        ['Premium Dry Fruits', 'No Dairy', 'Natural Sweetness', 'Vegan Ladoo'],
        ['Rich in Calcium', 'Low Sugar Content', 'Kid-Friendly Size', 'Real Cocoa'],
        ['High Protein Snack', 'Pure Honey Sweetened', 'No Preservatives', 'Perfect for Lunch Box'],
        ['Vitamin Rich Mix', 'Essential Minerals', 'Immunity Boosting', 'Kid Approved'],
        ['Natural Turmeric', 'Immunity Booster', 'Anti-Inflammatory', 'Jaggery Sweetened'],
    ];

    const allHighlights = insertedProducts.flatMap((product, productIndex) => 
        highlightsData[productIndex].map((highlight, index) => ({
            productId: product.id,
            highlightText: highlight,
            displayOrder: index + 1,
            createdAt: new Date(),
        }))
    );

    await db.insert(productHighlights).values(allHighlights);

    const ingredientsData = [
        ['Ragi Flour', 'Dark Chocolate', 'Walnuts', 'Dates', 'Coconut Oil', 'Cardamom'],
        ['Quinoa Flour', 'Ripe Bananas', 'Whole Wheat Flour', 'Honey', 'Baking Soda'],
        ['Jowar Flour', 'Bajra Flour', 'Ragi Flour', 'Oats', 'Sesame Seeds', 'Jaggery'],
        ['Besan', 'Pure Ghee', 'Jaggery', 'Cardamom Powder', 'Almond Flakes'],
        ['Jowar Flour', 'Fresh Coconut', 'Stevia', 'Baking Powder', 'Coconut Oil'],
        ['Whole Wheat Flour', 'Dates', 'Walnuts', 'Flax Seeds', 'Cinnamon'],
        ['Almond Flour', 'Pure Ghee', 'Jaggery', 'Cardamom', 'Pistachios'],
        ['Whole Wheat Flour', 'Sesame Seeds', 'Jaggery', 'Pure Ghee', 'Cardamom'],
        ['Ragi Flour', 'Cumin Seeds', 'Sesame Seeds', 'Rock Salt', 'Turmeric'],
        ['Bajra Flour', 'Red Chili Powder', 'Cumin Powder', 'Rock Salt', 'Sesame Oil'],
        ['Puffed Quinoa', 'Dates', 'Almonds', 'Cashews', 'Chia Seeds', 'Honey'],
        ['Amaranth Seeds', 'Jaggery', 'Peanuts', 'Sesame Seeds', 'Cardamom'],
        ['Ragi Flour', 'Jowar Flour', 'Bajra Flour', 'Amaranth Flour', 'Brown Rice Flour', 'Spices'],
        ['Ragi Flour', 'Cumin Seeds', 'Sesame Seeds', 'Pure Ghee', 'Asafoetida'],
        ['Jowar Puffs', 'Roasted Peanuts', 'Chaat Masala', 'Rock Salt', 'Lemon Juice'],
        ['Bajra Flour', 'Fresh Methi Leaves', 'Cumin Seeds', 'Sesame Seeds', 'Rock Salt'],
        ['Fresh Coconut', 'Medjool Dates', 'Almonds', 'Chia Seeds', 'Vanilla Extract'],
        ['Roasted Cashews', 'Dried Cranberries', 'Dates', 'Coconut Oil', 'Vanilla'],
        ['Roasted Peanuts', 'Organic Jaggery', 'Sesame Seeds', 'Cardamom'],
        ['Dates', 'Almonds', 'Cashews', 'Pistachios', 'Raisins', 'Coconut'],
        ['Ragi Flour', 'Cocoa Powder', 'Dates', 'Coconut Sugar', 'Vanilla Extract'],
        ['Rolled Oats', 'Pure Honey', 'Almonds', 'Pumpkin Seeds', 'Cinnamon'],
        ['Dried Mango', 'Raisins', 'Almonds', 'Cashews', 'Pumpkin Seeds', 'Sunflower Seeds'],
        ['Turmeric Powder', 'Jaggery', 'Brown Rice Flour', 'Coconut Oil', 'Cardamom'],
    ];

    const allIngredients = insertedProducts.flatMap((product, productIndex) => 
        ingredientsData[productIndex].map((ingredient, index) => ({
            productId: product.id,
            ingredientName: ingredient,
            displayOrder: index + 1,
            createdAt: new Date(),
        }))
    );

    await db.insert(productIngredients).values(allIngredients);

    console.log('✅ Products seeder completed successfully - Added 24 new products with images, nutrition, highlights, and ingredients');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});